### ISSUE TITLE
Vanilla's Beacon reskin seemingly removed beacon-antenna.png

### ISSUE THREAD

**Issue by danopia** [figsoda/ats#1]
Just looking at starting a shunting yard project and this mod failed to load up after install, even on its own. Sounds like ATS was using the old beacon's rotating antenna animation but it doesn't exist anymore: https://factorio.com/blog/post/fff-351

![Screenshot 2020-07-08 at 13 46 05](https://user-images.githubusercontent.com/40628/86915077-a97f5f80-c121-11ea-8c7d-a037e847d557.png)

**Comment by figsoda** [comment]
Should be fixed in v0.3.0
